# Generated by Django 2.1.5 on 2019-02-05 02:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(max_length=500)),
                ('dev', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None)),
                ('pub', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None)),
                ('name', models.CharField(max_length=500)),
                ('price', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('previous_price', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('short_desc', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('dlc', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('genres', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('platforms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('release_date', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteamProfile',
            fields=[
                ('id64', models.IntegerField(primary_key=True, serialize=False)),
                ('vanity_url', models.CharField(blank=True, max_length=500)),
                ('steam_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('real_name', models.CharField(blank=True, max_length=500)),
                ('profile_state', models.IntegerField(blank=True, null=True)),
                ('primary_clan', models.IntegerField(blank=True, null=True)),
                ('loc_country', models.CharField(blank=True, max_length=10, null=True)),
                ('loc_state', models.CharField(blank=True, max_length=10, null=True)),
                ('loc_city', models.IntegerField(blank=True, null=True)),
                ('in_game', models.IntegerField(blank=True, null=True)),
                ('in_game_name', models.CharField(blank=True, max_length=500)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('avatar_med', models.URLField(blank=True, null=True)),
                ('avatar_full', models.URLField(blank=True, null=True)),
                ('games_owned', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('friends', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('bans', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('badges', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('last_online', models.IntegerField(blank=True, null=True)),
                ('time_created', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
