# Generated by Django 2.1.5 on 2019-02-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamprofile',
            name='id64',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
