# Generated by Django 2.1.5 on 2019-02-07 02:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190207_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamprofile',
            name='recent_games',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
