# Generated by Django 2.1.5 on 2019-02-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_steamprofile_recent_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamprofile',
            name='primary_clan',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
