# Generated by Django 2.1.5 on 2019-02-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190207_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamprofile',
            name='visibility',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
