# Generated by Django 2.1.7 on 2019-03-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_steamprofile_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortProfile',
            fields=[
                ('id64', models.BigIntegerField(primary_key=True, serialize=False)),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('profile_state', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('real_name', models.CharField(blank=True, max_length=500)),
                ('primary_clan', models.BigIntegerField(blank=True, null=True)),
                ('loc_country', models.CharField(blank=True, max_length=10, null=True)),
                ('loc_state', models.CharField(blank=True, max_length=10, null=True)),
                ('loc_city', models.IntegerField(blank=True, null=True)),
                ('in_game', models.IntegerField(blank=True, null=True)),
                ('in_game_name', models.CharField(blank=True, max_length=500)),
                ('last_online', models.IntegerField(blank=True, null=True)),
                ('time_created', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
