# Generated by Django 2.1.7 on 2019-03-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190307_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortprofile',
            name='steam_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
