# Generated by Django 2.1.7 on 2019-03-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shortprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortprofile',
            name='id64',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shortprofile',
            name='primary_clan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steamprofile',
            name='id64',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='steamprofile',
            name='primary_clan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
