# Generated by Django 2.1.7 on 2019-03-12 00:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190308_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('gameid', models.CharField(max_length=500)),
                ('image', models.URLField(blank=True, null=True)),
                ('image2', models.URLField(blank=True, null=True)),
                ('image3', models.URLField(blank=True, null=True)),
                ('image4', models.URLField(blank=True, null=True)),
                ('image5', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('xp', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('cards', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
