# Generated by Django 2.1.7 on 2019-03-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='badgeid',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='badges',
            name='gameid',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='badges',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='badges',
            name='level',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badges',
            name='xp',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
