# Generated by Django 2.1.7 on 2019-03-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190312_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='unlocked',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
