# Generated by Django 2.1.7 on 2019-03-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_badges_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
